create or replace view {{SF_DATABASE}}.{{SF_CONSUMPTION_SCHEMA}}.VW_REVENUE(
	STORENAME,
	STOREID,
	TRANSACTIONDATE,
	AMOUNT,
    MODEOFSERVICE,
	OPERATING_COST
) as select * from {{SF_DATABASE}}.{{SF_TRANSFORMATION_SCHEMA}}.revenue;


create or replace view {{SF_DATABASE}}.{{SF_CONSUMPTION_SCHEMA}}.VW_SERVICEMETRICS(
	STORENAME,
	STOREID,
	TRANSACTIONDATE,
	TRANSACTIONID,
	AMOUNT,
     MODEOFSERVICE,
	SERVICETYPE
) as select * from {{SF_DATABASE}}.{{SF_TRANSFORMATION_SCHEMA}}.servicemetrics;

create or replace view {{SF_DATABASE}}.{{SF_CONSUMPTION_SCHEMA}}.VW_STORE_INSIGHTS(
	STORENAME,
	STOREID,
	TRANSACTIONDATE,
	MACHINEID,
	STATUS,
	AMOUNT,
	MODEOFSERVICE,
	EMPLOYEEID
) as select * from {{SF_DATABASE}}.{{SF_TRANSFORMATION_SCHEMA}}.store_insights;

create or replace view {{SF_DATABASE}}.{{SF_CONSUMPTION_SCHEMA}}.VW_STORE_RATINGS(
	STORENAME,
	TRANSACTIONDATE,
      MODEOFSERVICE,
	RATING
) as select * from {{SF_DATABASE}}.{{SF_TRANSFORMATION_SCHEMA}}.store_ratings;
